# MoveIt-specific simulation settings
moveit_sim_hw_interface:
  joint_model_group: controllers_initial_group_
  joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - left_arm_1_joint
    - left_arm_2_joint
    - left_arm_3_joint
    - left_arm_4_joint
    - left_arm_5_joint
    - left_arm_6_joint
    - left_hand_finger_22_joint
    - left_hand_finger_23_joint
    - left_hand_knuckle_joint
    - left_hand_finger_12_joint
    - left_hand_finger_13_joint
    - left_hand_thumb_2_joint
    - left_hand_thumb_3_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS

left_arm_trajectory:
  type: position_controllers/JointTrajectoryController
  joints:
    - left_arm_1_joint
    - left_arm_2_joint
    - left_arm_3_joint
    - left_arm_4_joint
    - left_arm_5_joint
    - left_arm_6_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    left_arm_1_joint: {trajectory: 0.1, goal: 0.1}
    left_arm_2_joint: {trajectory: 0.1, goal: 0.1}
    left_arm_3_joint: {trajectory: 0.1, goal: 0.1}
    left_arm_4_joint: {trajectory: 0.1, goal: 0.1}
    left_arm_5_joint: {trajectory: 0.1, goal: 0.1}
    left_arm_6_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  required_drive_mode: 7

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
left_arm_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - left_arm_1_joint
    - left_arm_2_joint
    - left_arm_3_joint
    - left_arm_4_joint
    - left_arm_5_joint
    - left_arm_6_joint
  required_drive_mode: 1
  pid: {p: 50.0, i: 0.01, d: 10.0}
left_hand_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - left_hand_finger_21_joint
    - left_hand_knuckle_joint
    - left_hand_finger_12_joint
    - left_hand_finger_13_joint
    - left_hand_finger_22_joint
    - left_hand_finger_23_joint
    - left_hand_thumb_2_joint
    - left_hand_thumb_3_joint
  required_drive_mode: 1
  pid: {p: 50.0, i: 0.01, d: 10.0}